### ISSUE TITLE
Emojis rendering issue

### ISSUE THREAD

**Issue by Quy** [ModernBB/Luna#1065]
Some emojiis are not rendering.
(https://dl.dropboxusercontent.com/u/4284608/smilies.jpg)

Windows Vista Business Service Pack 2
Tested with:
Firefox 35
Chrome Version 39.0.2171.99
IE 9

**Comment by Studio384** [comment]
That's because Windows Vista (and XP) can't display emojis. I'm not to certain if that 2,9% (currently), is worth supporting. There aren't much Vista users out there anymore. Now, 80-85% of the people out there can see Emojis.

**Comment by Quy** [comment]
OK. I guess there is nothing to do here except to upgrade the OS. 
On a related note, size 14px is a tad small so it is hard to make out the smilies.
