### ISSUE TITLE
Wrong size of search button

### ISSUE THREAD

**Issue by alvr** [ModernBB/Luna#1077]
With ```!important``` in the ```btn``` class, the search icon is not showing correctly.

**With !important**
![With !important](https://cloud.githubusercontent.com/assets/217315/5922056/e077a0c8-a648-11e4-8f04-0309849019c6.png)

**Without !important**
![Without !important](https://cloud.githubusercontent.com/assets/217315/5922055/e071c554-a648-11e4-87ea-2c423df2cad7.png)

I'm using Chrome 40.0.2214.93 on Windows x64 8.1

PS: This also happens on getluna.org forum.

Commit: 79c819f

**Comment by Studio384** [comment]
This should be fixed, we'll be pushing this later.
